// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-G9MX02KuOgYLuf2-VLFDGLbrnu21rA',
    appId: '1:1062926937674:web:324160bb4eee505301c0b3',
    messagingSenderId: '1062926937674',
    projectId: 'craftmyplate-8f3a1',
    authDomain: 'craftmyplate-8f3a1.firebaseapp.com',
    storageBucket: 'craftmyplate-8f3a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-qGLfsBEemUuTTm1jFVXdAE0jQg29iU',
    appId: '1:1062926937674:android:0d265f82e440803f01c0b3',
    messagingSenderId: '1062926937674',
    projectId: 'craftmyplate-8f3a1',
    storageBucket: 'craftmyplate-8f3a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8fgSIIlLrLt158geVV2yjnjPfChHYwBY',
    appId: '1:1062926937674:ios:71081969df14f50201c0b3',
    messagingSenderId: '1062926937674',
    projectId: 'craftmyplate-8f3a1',
    storageBucket: 'craftmyplate-8f3a1.appspot.com',
    iosClientId: '1062926937674-v8a7de88722lp0nf58pl9nrbmcosf2bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftmyplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8fgSIIlLrLt158geVV2yjnjPfChHYwBY',
    appId: '1:1062926937674:ios:7cede539bb1230d801c0b3',
    messagingSenderId: '1062926937674',
    projectId: 'craftmyplate-8f3a1',
    storageBucket: 'craftmyplate-8f3a1.appspot.com',
    iosClientId: '1062926937674-v9u1s45fu165gbotd6br4f1b8af5h6fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftmyplate.RunnerTests',
  );
}
